---

- name: add sendgrid credential type
  awx.awx.credential_type:
    name: sendgrid
    description: sengrid api
    kind: cloud
    inputs:
      fields:
        - type: string
          id: sendgrid_user
          label: Username
        - type: string
          id: sendgrid_from_email_address
          label: From email address
        - secret: true
          type: string
          id: sendgrid_api_key
          label: Api key
      required:
        - sendgrid_user
        - sendgrid_from_email_address
        - sendgrid_api_key
    injectors:
      extra_vars:
        sendgrid_user: '{% raw %}{{ sendgrid_user }}{% endraw %}'
        sendgrid_from_email_address: '{% raw %}{{ sendgrid_from_email_address }}{% endraw %}'
        sendgrid_api_key: '{% raw %}{{ sendgrid_api_key }}{% endraw %}'
    state: present
    controller_host: '{{ controller_host }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: '{{ controller_verify_ssl }}'
  register: reg_credential_type_sendgrid
  until: reg_credential_type_sendgrid is success
  delay: 3
  retries: 300

- name: add smtp credential type
  awx.awx.credential_type:
    name: smtp
    description: smtp
    kind: cloud
    inputs:
      fields:
        - type: string
          id: smtp_server_host
          label: SMTP Server Host
        - type: string
          id: smtp_server_port
          label: SMTP Server Port
        - type: string
          id: smtp_account
          label: SMTP Username
        - secret: true
          type: string
          id: smtp_account_password
          label: SMTP User Password
        - type: string
          id: smtp_from_email_address
          label: SMTP From Email Address
      required:
        - smtp_server_host
        - smtp_server_port
    injectors:
      extra_vars:
        smtp_account: '{% raw %}{{ smtp_account | default(None) }}{% endraw %}'
        smtp_server_host: '{% raw %}{{ smtp_server_host }}{% endraw %}'
        smtp_server_port: '{% raw %}{{ smtp_server_port }}{% endraw %}'
        smtp_account_password: '{% raw %}{{ smtp_account_password | default(None) }}{% endraw %}'
        smtp_from_email_address: '{% raw %}{{ smtp_from_email_address }}{% endraw %}'
    state: present
    controller_host: '{{ controller_host }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: '{{ controller_verify_ssl }}'
  register: reg_credential_type_smtp
  until: reg_credential_type_smtp is success
  delay: 3
  retries: 300